// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cookie-cloud/add-or-update": {
            "post": {
                "description": "添加或更新cookie cloud配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cookie cloud"
                ],
                "summary": "添加或更新cookie cloud配置",
                "parameters": [
                    {
                        "description": "cookie cloud配置",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/db.CookieCloudConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/cookie-cloud/get": {
            "get": {
                "description": "获取cookie cloud配置",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cookie cloud"
                ],
                "summary": "获取cookie cloud配置",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "db.CookieCloudConfig": {
            "type": "object",
            "properties": {
                "p2p_password": {
                    "description": "端对端加密密码",
                    "type": "string"
                },
                "sync_cron": {
                    "description": "同步cron表达式",
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "user_key": {
                    "description": "用户KEY",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Seed Sync API",
	Description:      "This is a seed sync server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
